# Generated by Django 4.2 on 2024-12-29 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_city_options_alter_user_phone_number'),
        ('cars', '0002_announcement_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcements', to='accounts.city'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='is_showroom',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='announcement',
            name='is_vip',
            field=models.BooleanField(default=False),
        ),
    ]
