# Generated by Django 4.2 on 2024-12-29 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_announcement_city_announcement_is_showroom_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcementimage',
            name='announcement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcement_images', to='cars.announcement'),
        ),
    ]
