# Generated by Django 4.2 on 2024-12-29 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_alter_announcementimage_announcement'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='number_of_views',
            field=models.IntegerField(default=0),
        ),
    ]
