# Generated by Django 4.2 on 2024-12-29 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_announcement_number_of_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='is_new',
            field=models.BooleanField(default=False),
        ),
    ]
