# Generated by Django 4.2 on 2025-01-05 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_announcement_is_new'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='is_dealer',
            field=models.BooleanField(default=False),
        ),
    ]
