# Generated by Django 4.2 on 2024-11-09 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_fullname', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=50)),
                ('about', models.TextField()),
                ('published_date', models.DateTimeField()),
            ],
        ),
    ]
