# Generated by Django 4.2 on 2024-11-16 11:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blogs', '0006_alter_blog_published_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='author_fullname',
        ),
        migrations.AddField(
            model_name='blog',
            name='author',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
