# Generated by Django 4.2 on 2024-11-30 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0010_blog_categories'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
    ]
