# Generated by Django 4.2 on 2024-11-30 12:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0012_blog_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='published_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 11, 30, 12, 20, 56, 409678, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
