# Generated by Django 4.2 on 2024-12-01 07:14

import core.utils.image_size_validator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0013_alter_blog_published_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media', validators=[core.utils.image_size_validator.validate_image]),
        ),
    ]
